[theme]
base                     = "dark"
backgroundColor          = "#0A0A0F"
secondaryBackgroundColor = "#12121A"
textColor                = "#F0F0F0"
primaryColor             = "#89C4E1"

[server]
headless = true
