[theme]
base                     = "dark"
backgroundColor          = "#0A0A0D"
secondaryBackgroundColor = "#131316"
textColor                = "#F5F5F7"
primaryColor             = "#FC4C02"

[server]
headless = true
